"""
Trading Strategies Module

Implements various trading strategies including SuperTrend, RL-based, and hybrid approaches.
"""

import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime
import numpy as np

logger = logging.getLogger(__name__)


def _run_backtest(
    strategy: "BaseStrategy",
    symbol: str,
    period: str,
    config: Dict[str, Any],
) -> Dict[str, Any]:
    """Run the event-driven backtester for a strategy over historical data.

    Fetches OHLCV data for ``symbol`` and replays it through
    :func:`utils.backtest.backtest_strategy`, returning a serializable summary
    that includes the full performance report. Imports are done lazily to avoid
    import cycles and keep optional dependencies isolated.
    """
    try:
        from utils.backtest import backtest_strategy
        from utils.data_fetcher import fetch_market_data
        from utils.performance import periods_per_year_for

        limit = _period_to_bars(period)
        timeframe = config.get('trading', {}).get('default_timeframe', '1h')
        market_data = fetch_market_data(symbol, timeframe, limit=limit)

        if not market_data or not market_data.get('close'):
            return {
                'strategy': strategy.name,
                'symbol': symbol,
                'period': period,
                'error': 'No market data available for backtest',
            }

        bt_config = dict(config.get('backtesting', {}))
        bt_config.setdefault('periods_per_year', periods_per_year_for(timeframe))
        # Inherit risk parameters from the strategy where available.
        bt_config.setdefault('atr_period', strategy.parameters.get('atr_period', 14))

        # Strategy-specific preparation (e.g. RL training on the in-sample part).
        extra = strategy.before_backtest(market_data, bt_config) or {}

        result = backtest_strategy(strategy, market_data, bt_config)
        result.update(extra)
        result.update({'strategy': strategy.name, 'symbol': symbol, 'period': period})
        # Keep the equity curve out of the lightweight summary for readability.
        result.pop('equity_curve', None)
        return result

    except Exception as e:  # pragma: no cover - defensive
        logger.error(f"Backtest failed for {strategy.name} on {symbol}: {e}")
        return {
            'strategy': strategy.name,
            'symbol': symbol,
            'period': period,
            'error': str(e),
        }


def _period_to_bars(period: str, default: int = 500) -> int:
    """Translate a period string like ``'90d'`` into an approximate bar count."""
    try:
        period = period.strip().lower()
        if period.endswith('d'):
            return max(int(period[:-1]) * 24, 50)  # assume hourly bars
        if period.endswith('w'):
            return max(int(period[:-1]) * 24 * 7, 50)
        if period.endswith('h'):
            return max(int(period[:-1]), 50)
        return max(int(period), 50)
    except (ValueError, AttributeError):
        return default


@dataclass
class StrategySignal:
    """Signal generated by a trading strategy"""
    action: str  # 'buy', 'sell', 'hold', or 'exit' (close any position)
    confidence: float
    price: float
    timestamp: datetime
    indicators: Dict[str, float]
    reasoning: str


class BaseStrategy(ABC):
    """Base class for all trading strategies"""

    # Key under ``strategies.parameters`` in the engine config.
    config_key: Optional[str] = None

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.parameters = self._resolve_parameters(config)
        self.name = self.__class__.__name__

    def _resolve_parameters(self, config: Dict[str, Any]) -> Dict[str, Any]:
        """Strategy parameters, from either a direct ``parameters`` dict or the
        engine config's ``strategies.parameters.<config_key>`` section."""
        if config.get('parameters') is not None:
            return dict(config['parameters'])
        section = (config.get('strategies') or {}).get('parameters') or {}
        return dict(section.get(self.config_key) or {})

    def before_backtest(self, ohlcv: Dict[str, Any], bt_config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Hook run before :meth:`backtest` replays data. May adjust
        ``bt_config`` in place and return extra fields for the result."""
        return None

    @abstractmethod
    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate trading signal from market data"""
        pass

    @abstractmethod
    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest the strategy"""
        pass

    def set_parameters(self, parameters: Dict[str, Any]):
        """Update strategy parameters. If the new values are rejected, the
        previous parameters are restored and the error is re-raised."""
        previous = dict(self.parameters)
        self.parameters.update(parameters)
        try:
            self._on_parameters_changed()
        except Exception:
            self.parameters.clear()
            self.parameters.update(previous)
            self._on_parameters_changed()
            raise

    def _on_parameters_changed(self) -> None:
        """Re-read derived attributes after :meth:`set_parameters`."""

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters"""
        return self.parameters.copy()


class SuperTrendStrategy(BaseStrategy):
    """
    SuperTrend Indicator Strategy

    Uses ATR-based dynamic support/resistance levels for trend following.
    """

    config_key = 'supertrend'

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self._on_parameters_changed()

    def _on_parameters_changed(self) -> None:
        self.atr_period = self.parameters.get('atr_period', 10)
        self.multiplier = self.parameters.get('multiplier', 3.0)

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate SuperTrend signal for the most recent bar.

        Emits a ``buy``/``sell`` only when the trend direction flips on the
        latest bar (a genuine crossover), otherwise ``hold``. The SuperTrend
        line and direction arrays are index-aligned with ``close`` so the signal
        always reflects the current bar (no off-by-one drift).
        """

        try:
            # Extract OHLC data
            high = market_data.get('high', [])
            low = market_data.get('low', [])
            close = market_data.get('close', [])

            if len(close) < self.atr_period + 1:
                logger.warning("Insufficient data for SuperTrend calculation")
                return None

            supertrend, direction, atr = self._calculate_supertrend(high, low, close)

            current_price = close[-1]
            current_st = supertrend[-1]
            current_direction = direction[-1]
            prev_direction = direction[-2] if len(direction) > 1 else current_direction

            indicators = {
                'supertrend': current_st,
                'atr': atr[-1],
                'direction': current_direction,
            }

            if current_direction == 1 and prev_direction == -1:
                return StrategySignal(
                    action='buy',
                    confidence=0.8,
                    price=current_price,
                    timestamp=datetime.now(),
                    indicators=indicators,
                    reasoning=f"Price crossed above SuperTrend line at {current_price:.2f}",
                )

            if current_direction == -1 and prev_direction == 1:
                return StrategySignal(
                    action='sell',
                    confidence=0.8,
                    price=current_price,
                    timestamp=datetime.now(),
                    indicators=indicators,
                    reasoning=f"Price crossed below SuperTrend line at {current_price:.2f}",
                )

            return StrategySignal(
                action='hold',
                confidence=0.5,
                price=current_price,
                timestamp=datetime.now(),
                indicators=indicators,
                reasoning="No trend change detected",
            )

        except Exception as e:
            logger.error(f"Error generating SuperTrend signal: {e}")
            return None

    def _calculate_supertrend(
        self,
        high: List[float],
        low: List[float],
        close: List[float],
    ) -> tuple:
        """Calculate the SuperTrend line, direction and ATR.

        All three returned lists are aligned to ``close`` indices (length n).
        ``direction`` uses 1 for uptrend and -1 for downtrend.
        """
        from utils.indicators import calculate_supertrend

        return calculate_supertrend(high, low, close, self.atr_period, self.multiplier)

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest the SuperTrend strategy on historical/market data.

        Uses the event-driven :class:`~utils.backtest.Backtester` with the
        strategy's configured risk parameters. Falls back gracefully if data is
        unavailable.
        """
        return _run_backtest(self, symbol, period, self.config)


class RLStrategy(BaseStrategy):
    """
    Reinforcement Learning Strategy

    A tabular Q-learning agent (see :mod:`strategies.rl`) that maps a discrete
    market state plus the current position to a target position (flat, long
    or short). Signals: target long -> ``buy``, target short -> ``sell``,
    target flat -> ``exit`` (or ``hold`` when already flat).

    The agent is loaded from ``model_path`` when a compatible saved model
    exists, trained explicitly with :meth:`train`, or trained on the in-sample
    part of the data automatically by :meth:`backtest`. Until it is trained it
    only emits ``hold``.

    The current position is read from ``market_data['position']`` (1, -1 or 0;
    the backtester provides it). Callers that omit it are treated as flat.
    """

    config_key = 'rl_agent'

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.agent = None
        self.agent_source: Optional[str] = None  # 'trained' or 'loaded'
        self.training_summary: Optional[Dict[str, Any]] = None
        self._prepared: Optional[Dict[str, Any]] = None
        self._on_parameters_changed()
        if self.rl_config.load_model and self.rl_config.model_path:
            self.load()

    def _on_parameters_changed(self) -> None:
        from strategies.rl import RLConfig

        self.rl_config = RLConfig.from_params(self.parameters)
        self._prepared = None
        if self.agent is not None and not self._agent_matches_config(self.agent):
            logger.warning("RL parameters changed; discarding the incompatible trained agent")
            self.agent = None
            self.agent_source = None

    @property
    def is_trained(self) -> bool:
        return self.agent is not None

    # ------------------------------------------------------------------ #
    # Training & persistence
    # ------------------------------------------------------------------ #
    def train(self, ohlcv: Dict[str, Any], end: Optional[int] = None) -> Dict[str, Any]:
        """Train the agent on bars ``[0, end)`` of ``ohlcv``.

        Returns a training summary. Saves to ``model_path`` if ``save_model``.
        """
        from strategies.rl import compute_market_states, train_agent

        states = compute_market_states(ohlcv, self.rl_config.features)
        result = train_agent(ohlcv, self.rl_config, end=end, market_states=states)
        self.agent = result.agent
        self.agent_source = 'trained'
        self.training_summary = result.summary()
        self._cache_states(ohlcv, states)
        if self.rl_config.save_model and self.rl_config.model_path:
            self.save()
        return self.training_summary

    def save(self, path: Optional[str] = None) -> str:
        if self.agent is None:
            raise RuntimeError("RL agent is not trained; nothing to save")
        target = path or self.rl_config.model_path
        if not target:
            raise ValueError("no model_path configured")
        return str(self.agent.save(target))

    def load(self, path: Optional[str] = None) -> bool:
        """Load a saved agent. Returns False (keeping the current agent) if the
        file is missing, unreadable, or was trained with different settings."""
        from pathlib import Path
        from strategies.rl import QLearningAgent

        source = path or self.rl_config.model_path
        if not source or not Path(source).exists():
            return False
        try:
            agent = QLearningAgent.load(source)
        except (OSError, ValueError, KeyError) as e:
            logger.warning(f"Could not load RL model from {source}: {e}")
            return False
        if not self._agent_matches_config(agent):
            logger.warning(f"RL model at {source} was trained with different settings; ignoring it")
            return False
        self.agent = agent
        self.agent_source = 'loaded'
        logger.info(f"Loaded RL agent from {source}")
        return True

    def _agent_matches_config(self, agent) -> bool:
        return (
            agent.metadata.get('features') == self.rl_config.features.to_dict()
            and agent.allow_short == self.rl_config.allow_short
        )

    # ------------------------------------------------------------------ #
    # Signals
    # ------------------------------------------------------------------ #
    def prepare(self, ohlcv: Dict[str, Any]) -> None:
        """Precompute market states for a full series. Because states are
        causal, later windows that are prefixes of this series reuse them."""
        from strategies.rl import compute_market_states

        cached = self._prepared
        if cached is not None and list(ohlcv.get('close', [])) == cached['close'] \
                and list(ohlcv.get('high', [])) == cached['high'] \
                and list(ohlcv.get('low', [])) == cached['low']:
            return
        self._cache_states(ohlcv, compute_market_states(ohlcv, self.rl_config.features))

    def _cache_states(self, ohlcv: Dict[str, Any], states: List[Optional[int]]) -> None:
        self._prepared = {
            'close': list(ohlcv.get('close', [])),
            'high': list(ohlcv.get('high', [])),
            'low': list(ohlcv.get('low', [])),
            'states': states,
        }

    def _market_state(self, market_data: Dict[str, Any]) -> Optional[int]:
        close = market_data.get('close', [])
        n = len(close)
        cached = self._prepared
        if (
            cached is not None
            and 0 < n <= len(cached['close'])
            and list(close) == cached['close'][:n]
            and list(market_data.get('high', close)) == cached['high'][:n]
            and list(market_data.get('low', close)) == cached['low'][:n]
        ):
            return cached['states'][n - 1]

        from strategies.rl import compute_market_states

        return compute_market_states(market_data, self.rl_config.features)[-1] if n else None

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate a signal from the trained agent's greedy policy."""
        from strategies.rl import ACTION_NAMES, FLAT, LONG, SHORT, agent_state, decode_market_state

        close = market_data.get('close') or [0]
        price = close[-1]
        position = int(market_data.get('position', 0) or 0)
        position = max(-1, min(1, position))
        if position == -1 and not self.rl_config.allow_short:
            position = 0

        def hold(reason: str, indicators: Optional[Dict[str, Any]] = None) -> StrategySignal:
            return StrategySignal(
                action='hold', confidence=0.0, price=price, timestamp=datetime.now(),
                indicators=indicators or {'position': position}, reasoning=reason,
            )

        if self.agent is None:
            return hold("RL agent is not trained yet (call train() or backtest())")

        market_state = self._market_state(market_data)
        if market_state is None:
            return hold("Not enough history for RL state features")

        state = agent_state(market_state, position)
        action = self.agent.greedy_action(state)
        confidence = self.agent.confidence(state)
        q = self.agent.q_values(state)

        if action == LONG:
            signal_action = 'buy'
        elif action == SHORT:
            signal_action = 'sell'
        else:
            signal_action = 'exit' if position != 0 else 'hold'

        indicators: Dict[str, Any] = {
            'position': position,
            'target': ACTION_NAMES[action],
            'market_state': market_state,
            'state_visits': int(self.agent.visits[state].sum()),
            **{f'q_{ACTION_NAMES[a]}': v for a, v in q.items()},
            **decode_market_state(market_state),
        }
        if indicators['state_visits'] == 0:
            return hold("State never seen in training; staying put", indicators)

        return StrategySignal(
            action=signal_action,
            confidence=confidence,
            price=price,
            timestamp=datetime.now(),
            indicators=indicators,
            reasoning=f"RL agent targets {ACTION_NAMES[action]} (Q-margin confidence {confidence:.2f})",
        )

    # ------------------------------------------------------------------ #
    # Backtesting
    # ------------------------------------------------------------------ #
    def before_backtest(self, ohlcv: Dict[str, Any], bt_config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Train on the first ``train_fraction`` of the data and only trade the
        remaining, unseen part.

        An agent loaded from ``model_path`` is used as-is (trading still starts
        at the split). An agent trained earlier in memory is always retrained
        here, since it may have seen this backtest's out-of-sample bars or a
        different market entirely.
        """
        n = len(ohlcv.get('close', []))
        split = int(n * self.rl_config.train_fraction)
        info: Dict[str, Any] = {'rl_split_index': split}

        if self.agent_source != 'loaded':
            if split < self.rl_config.min_train_bars:
                raise ValueError(
                    f"Not enough data to train the RL agent: {split} in-sample bars, "
                    f"need {self.rl_config.min_train_bars}"
                )
            info['rl_training'] = self.train(ohlcv, end=split)
            info['rl_model_source'] = 'trained_in_sample'
        else:
            info['rl_model_source'] = 'loaded'

        bt_config['warmup'] = max(int(bt_config.get('warmup') or 0), split)
        bt_config.setdefault('allow_short', self.rl_config.allow_short)
        return info

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Train in-sample and backtest out-of-sample with the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


class MultiFactorStrategy(BaseStrategy):
    """
    Multi-Factor Strategy

    Combines multiple technical indicators and factors.
    """

    config_key = 'multi_factor'

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.factors = self.parameters.get('factors', ['trend', 'momentum', 'volatility'])
        self.weights = self.parameters.get('weights', [0.4, 0.4, 0.2])

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from multiple factors"""

        # Calculate factor scores
        trend_score = self._calculate_trend_score(market_data)
        momentum_score = self._calculate_momentum_score(market_data)
        volatility_score = self._calculate_volatility_score(market_data)

        # Weighted combination
        combined_score = (
            trend_score * self.weights[0] +
            momentum_score * self.weights[1] +
            volatility_score * self.weights[2]
        )

        # Determine action
        if combined_score > 0.6:
            action = 'buy'
        elif combined_score < 0.4:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=abs(combined_score - 0.5) * 2,
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={
                'combined_score': combined_score,
                'trend_score': trend_score,
                'momentum_score': momentum_score,
                'volatility_score': volatility_score
            },
            reasoning=f"Multi-factor score: {combined_score:.2f}"
        )

    def _calculate_trend_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate trend factor score"""
        # Placeholder - implement actual trend calculation
        return 0.7

    def _calculate_momentum_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate momentum factor score"""
        # Placeholder - implement actual momentum calculation
        return 0.6

    def _calculate_volatility_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate volatility factor score"""
        # Placeholder - implement actual volatility calculation
        return 0.5

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest multi-factor strategy using the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


class HybridStrategy(BaseStrategy):
    """
    Hybrid Strategy

    Combines multiple strategies with ensemble logic.
    """

    config_key = 'hybrid'

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.strategies = [
            SuperTrendStrategy(config),
            MultiFactorStrategy(config)
        ]

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from ensemble of strategies"""

        # Get signals from all strategies
        signals = []
        for strategy in self.strategies:
            signal = strategy.generate_signal(market_data)
            if signal:
                signals.append(signal)

        if not signals:
            return None

        # Ensemble logic: majority vote weighted by confidence
        buy_score = sum(s.confidence for s in signals if s.action == 'buy')
        sell_score = sum(s.confidence for s in signals if s.action == 'sell')
        hold_score = sum(s.confidence for s in signals if s.action == 'hold')

        max_score = max(buy_score, sell_score, hold_score)

        if max_score == buy_score:
            action = 'buy'
        elif max_score == sell_score:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=max_score / len(signals),
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={'ensemble_score': max_score},
            reasoning=f"Ensemble decision from {len(signals)} strategies"
        )

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest hybrid strategy using the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


# Strategy registry
STRATEGY_REGISTRY = {
    'supertrend': SuperTrendStrategy,
    'rl_agent': RLStrategy,
    'multi_factor': MultiFactorStrategy,
    'hybrid': HybridStrategy
}


def get_strategy(strategy_name: str, config: Dict[str, Any]) -> BaseStrategy:
    """Factory function to get strategy instance"""

    strategy_class = STRATEGY_REGISTRY.get(strategy_name)

    if strategy_class is None:
        raise ValueError(f"Unknown strategy: {strategy_name}")

    return strategy_class(config)


def list_strategies() -> List[str]:
    """List available strategies"""
    return list(STRATEGY_REGISTRY.keys())


if __name__ == "__main__":
    # Example usage
    config = {
        'parameters': {
            'atr_period': 10,
            'multiplier': 3.0
        }
    }

    strategy = SuperTrendStrategy(config)

    # Mock market data
    market_data = {
        'high': [100 + i for i in range(20)],
        'low': [99 + i for i in range(20)],
        'close': [99.5 + i for i in range(20)]
    }

    signal = strategy.generate_signal(market_data)
    if signal:
        print(f"Signal: {signal.action} at {signal.price} (confidence: {signal.confidence})")
