"""
Trading Strategies Module

Implements various trading strategies including SuperTrend, RL-based, and hybrid approaches.
"""

import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime
import numpy as np

logger = logging.getLogger(__name__)


def _run_backtest(
    strategy: "BaseStrategy",
    symbol: str,
    period: str,
    config: Dict[str, Any],
) -> Dict[str, Any]:
    """Run the event-driven backtester for a strategy over historical data.

    Fetches OHLCV data for ``symbol`` and replays it through
    :func:`utils.backtest.backtest_strategy`, returning a serializable summary
    that includes the full performance report. Imports are done lazily to avoid
    import cycles and keep optional dependencies isolated.
    """
    try:
        from utils.backtest import backtest_strategy
        from utils.data_fetcher import fetch_market_data
        from utils.performance import periods_per_year_for

        limit = _period_to_bars(period)
        timeframe = config.get('trading', {}).get('default_timeframe', '1h')
        market_data = fetch_market_data(symbol, timeframe, limit=limit)

        if not market_data or not market_data.get('close'):
            return {
                'strategy': strategy.name,
                'symbol': symbol,
                'period': period,
                'error': 'No market data available for backtest',
            }

        bt_config = dict(config.get('backtesting', {}))
        bt_config.setdefault('periods_per_year', periods_per_year_for(timeframe))
        # Inherit risk parameters from the strategy where available.
        bt_config.setdefault('atr_period', strategy.parameters.get('atr_period', 14))

        result = backtest_strategy(strategy, market_data, bt_config)
        result.update({'strategy': strategy.name, 'symbol': symbol, 'period': period})
        # Keep the equity curve out of the lightweight summary for readability.
        result.pop('equity_curve', None)
        return result

    except Exception as e:  # pragma: no cover - defensive
        logger.error(f"Backtest failed for {strategy.name} on {symbol}: {e}")
        return {
            'strategy': strategy.name,
            'symbol': symbol,
            'period': period,
            'error': str(e),
        }


def _period_to_bars(period: str, default: int = 500) -> int:
    """Translate a period string like ``'90d'`` into an approximate bar count."""
    try:
        period = period.strip().lower()
        if period.endswith('d'):
            return max(int(period[:-1]) * 24, 50)  # assume hourly bars
        if period.endswith('w'):
            return max(int(period[:-1]) * 24 * 7, 50)
        if period.endswith('h'):
            return max(int(period[:-1]), 50)
        return max(int(period), 50)
    except (ValueError, AttributeError):
        return default


@dataclass
class StrategySignal:
    """Signal generated by a trading strategy"""
    action: str  # 'buy', 'sell', 'hold'
    confidence: float
    price: float
    timestamp: datetime
    indicators: Dict[str, float]
    reasoning: str


class BaseStrategy(ABC):
    """Base class for all trading strategies"""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.parameters = config.get('parameters', {})
        self.name = self.__class__.__name__

    @abstractmethod
    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate trading signal from market data"""
        pass

    @abstractmethod
    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest the strategy"""
        pass

    def set_parameters(self, parameters: Dict[str, Any]):
        """Update strategy parameters"""
        self.parameters.update(parameters)

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters"""
        return self.parameters.copy()


class SuperTrendStrategy(BaseStrategy):
    """
    SuperTrend Indicator Strategy

    Uses ATR-based dynamic support/resistance levels for trend following.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.atr_period = self.parameters.get('atr_period', 10)
        self.multiplier = self.parameters.get('multiplier', 3.0)

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate SuperTrend signal for the most recent bar.

        Emits a ``buy``/``sell`` only when the trend direction flips on the
        latest bar (a genuine crossover), otherwise ``hold``. The SuperTrend
        line and direction arrays are index-aligned with ``close`` so the signal
        always reflects the current bar (no off-by-one drift).
        """

        try:
            # Extract OHLC data
            high = market_data.get('high', [])
            low = market_data.get('low', [])
            close = market_data.get('close', [])

            if len(close) < self.atr_period + 1:
                logger.warning("Insufficient data for SuperTrend calculation")
                return None

            supertrend, direction, atr = self._calculate_supertrend(high, low, close)

            current_price = close[-1]
            current_st = supertrend[-1]
            current_direction = direction[-1]
            prev_direction = direction[-2] if len(direction) > 1 else current_direction

            indicators = {
                'supertrend': current_st,
                'atr': atr[-1],
                'direction': current_direction,
            }

            if current_direction == 1 and prev_direction == -1:
                return StrategySignal(
                    action='buy',
                    confidence=0.8,
                    price=current_price,
                    timestamp=datetime.now(),
                    indicators=indicators,
                    reasoning=f"Price crossed above SuperTrend line at {current_price:.2f}",
                )

            if current_direction == -1 and prev_direction == 1:
                return StrategySignal(
                    action='sell',
                    confidence=0.8,
                    price=current_price,
                    timestamp=datetime.now(),
                    indicators=indicators,
                    reasoning=f"Price crossed below SuperTrend line at {current_price:.2f}",
                )

            return StrategySignal(
                action='hold',
                confidence=0.5,
                price=current_price,
                timestamp=datetime.now(),
                indicators=indicators,
                reasoning="No trend change detected",
            )

        except Exception as e:
            logger.error(f"Error generating SuperTrend signal: {e}")
            return None

    def _calculate_supertrend(
        self,
        high: List[float],
        low: List[float],
        close: List[float],
    ) -> tuple:
        """Calculate the SuperTrend line, direction and ATR.

        All three returned lists are aligned to ``close`` indices (length n).
        ``direction`` uses 1 for uptrend and -1 for downtrend.
        """
        from utils.indicators import calculate_atr

        n = len(close)
        atr = calculate_atr(high, low, close, self.atr_period)

        hl2 = [(high[i] + low[i]) / 2 for i in range(n)]
        basic_upper = [hl2[i] + self.multiplier * atr[i] for i in range(n)]
        basic_lower = [hl2[i] - self.multiplier * atr[i] for i in range(n)]

        final_upper = [0.0] * n
        final_lower = [0.0] * n
        direction = [1] * n
        supertrend = [0.0] * n

        final_upper[0] = basic_upper[0]
        final_lower[0] = basic_lower[0]
        supertrend[0] = final_lower[0]

        for i in range(1, n):
            # Carry the band forward unless price/band movement allows a reset.
            if basic_upper[i] < final_upper[i - 1] or close[i - 1] > final_upper[i - 1]:
                final_upper[i] = basic_upper[i]
            else:
                final_upper[i] = final_upper[i - 1]

            if basic_lower[i] > final_lower[i - 1] or close[i - 1] < final_lower[i - 1]:
                final_lower[i] = basic_lower[i]
            else:
                final_lower[i] = final_lower[i - 1]

            prev_dir = direction[i - 1]
            if prev_dir == 1:
                direction[i] = -1 if close[i] < final_lower[i] else 1
            else:
                direction[i] = 1 if close[i] > final_upper[i] else -1

            supertrend[i] = final_lower[i] if direction[i] == 1 else final_upper[i]

        return supertrend, direction, atr

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest the SuperTrend strategy on historical/market data.

        Uses the event-driven :class:`~utils.backtest.Backtester` with the
        strategy's configured risk parameters. Falls back gracefully if data is
        unavailable.
        """
        return _run_backtest(self, symbol, period, self.config)


class RLStrategy(BaseStrategy):
    """
    Reinforcement Learning Strategy

    Uses trained RL agent for trading decisions.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.model_path = self.parameters.get('model_path', None)
        self._agent = None

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal using RL agent"""

        # Placeholder for RL agent
        # Future enhancement: Load and use actual trained RL model

        return StrategySignal(
            action='hold',
            confidence=0.6,
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={'rl_score': 0.6},
            reasoning="RL agent decision (placeholder)"
        )

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest RL strategy using the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


class MultiFactorStrategy(BaseStrategy):
    """
    Multi-Factor Strategy

    Combines multiple technical indicators and factors.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.factors = self.parameters.get('factors', ['trend', 'momentum', 'volatility'])
        self.weights = self.parameters.get('weights', [0.4, 0.4, 0.2])

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from multiple factors"""

        # Calculate factor scores
        trend_score = self._calculate_trend_score(market_data)
        momentum_score = self._calculate_momentum_score(market_data)
        volatility_score = self._calculate_volatility_score(market_data)

        # Weighted combination
        combined_score = (
            trend_score * self.weights[0] +
            momentum_score * self.weights[1] +
            volatility_score * self.weights[2]
        )

        # Determine action
        if combined_score > 0.6:
            action = 'buy'
        elif combined_score < 0.4:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=abs(combined_score - 0.5) * 2,
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={
                'combined_score': combined_score,
                'trend_score': trend_score,
                'momentum_score': momentum_score,
                'volatility_score': volatility_score
            },
            reasoning=f"Multi-factor score: {combined_score:.2f}"
        )

    def _calculate_trend_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate trend factor score"""
        # Placeholder - implement actual trend calculation
        return 0.7

    def _calculate_momentum_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate momentum factor score"""
        # Placeholder - implement actual momentum calculation
        return 0.6

    def _calculate_volatility_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate volatility factor score"""
        # Placeholder - implement actual volatility calculation
        return 0.5

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest multi-factor strategy using the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


class HybridStrategy(BaseStrategy):
    """
    Hybrid Strategy

    Combines multiple strategies with ensemble logic.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.strategies = [
            SuperTrendStrategy(config),
            MultiFactorStrategy(config)
        ]

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from ensemble of strategies"""

        # Get signals from all strategies
        signals = []
        for strategy in self.strategies:
            signal = strategy.generate_signal(market_data)
            if signal:
                signals.append(signal)

        if not signals:
            return None

        # Ensemble logic: majority vote weighted by confidence
        buy_score = sum(s.confidence for s in signals if s.action == 'buy')
        sell_score = sum(s.confidence for s in signals if s.action == 'sell')
        hold_score = sum(s.confidence for s in signals if s.action == 'hold')

        max_score = max(buy_score, sell_score, hold_score)

        if max_score == buy_score:
            action = 'buy'
        elif max_score == sell_score:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=max_score / len(signals),
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={'ensemble_score': max_score},
            reasoning=f"Ensemble decision from {len(signals)} strategies"
        )

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest hybrid strategy using the event-driven engine."""
        return _run_backtest(self, symbol, period, self.config)


# Strategy registry
STRATEGY_REGISTRY = {
    'supertrend': SuperTrendStrategy,
    'rl_agent': RLStrategy,
    'multi_factor': MultiFactorStrategy,
    'hybrid': HybridStrategy
}


def get_strategy(strategy_name: str, config: Dict[str, Any]) -> BaseStrategy:
    """Factory function to get strategy instance"""

    strategy_class = STRATEGY_REGISTRY.get(strategy_name)

    if strategy_class is None:
        raise ValueError(f"Unknown strategy: {strategy_name}")

    return strategy_class(config)


def list_strategies() -> List[str]:
    """List available strategies"""
    return list(STRATEGY_REGISTRY.keys())


if __name__ == "__main__":
    # Example usage
    config = {
        'parameters': {
            'atr_period': 10,
            'multiplier': 3.0
        }
    }

    strategy = SuperTrendStrategy(config)

    # Mock market data
    market_data = {
        'high': [100 + i for i in range(20)],
        'low': [99 + i for i in range(20)],
        'close': [99.5 + i for i in range(20)]
    }

    signal = strategy.generate_signal(market_data)
    if signal:
        print(f"Signal: {signal.action} at {signal.price} (confidence: {signal.confidence})")
