"""
Trading Strategies Module

Implements various trading strategies including SuperTrend, RL-based, and hybrid approaches.
"""

import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime
import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by a trading strategy"""
    action: str  # 'buy', 'sell', 'hold'
    confidence: float
    price: float
    timestamp: datetime
    indicators: Dict[str, float]
    reasoning: str


class BaseStrategy(ABC):
    """Base class for all trading strategies"""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.parameters = config.get('parameters', {})
        self.name = self.__class__.__name__

    @abstractmethod
    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate trading signal from market data"""
        pass

    @abstractmethod
    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest the strategy"""
        pass

    def set_parameters(self, parameters: Dict[str, Any]):
        """Update strategy parameters"""
        self.parameters.update(parameters)

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters"""
        return self.parameters.copy()


class SuperTrendStrategy(BaseStrategy):
    """
    SuperTrend Indicator Strategy

    Uses ATR-based dynamic support/resistance levels for trend following.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.atr_period = self.parameters.get('atr_period', 10)
        self.multiplier = self.parameters.get('multiplier', 3.0)

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate SuperTrend signal"""

        try:
            # Extract OHLC data
            high = market_data.get('high', [])
            low = market_data.get('low', [])
            close = market_data.get('close', [])

            if len(close) < self.atr_period + 1:
                logger.warning("Insufficient data for SuperTrend calculation")
                return None

            # Calculate ATR
            atr = self._calculate_atr(high, low, close)

            # Calculate SuperTrend
            basic_band_upper, basic_band_lower = self._calculate_bands(high, low, atr)
            supertrend, direction = self._calculate_supertrend(
                close, basic_band_upper, basic_band_lower
            )

            # Generate signal
            current_price = close[-1]
            current_st = supertrend[-1]
            current_direction = direction[-1]

            # Check for signal
            if len(direction) > 1:
                prev_direction = direction[-2]

                if current_direction == 1 and prev_direction == -1:
                    # Buy signal
                    return StrategySignal(
                        action='buy',
                        confidence=0.8,
                        price=current_price,
                        timestamp=datetime.now(),
                        indicators={
                            'supertrend': current_st,
                            'atr': atr[-1],
                            'direction': current_direction
                        },
                        reasoning=f"Price crossed above SuperTrend line at {current_price:.2f}"
                    )

                elif current_direction == -1 and prev_direction == 1:
                    # Sell signal
                    return StrategySignal(
                        action='sell',
                        confidence=0.8,
                        price=current_price,
                        timestamp=datetime.now(),
                        indicators={
                            'supertrend': current_st,
                            'atr': atr[-1],
                            'direction': current_direction
                        },
                        reasoning=f"Price crossed below SuperTrend line at {current_price:.2f}"
                    )

            # No signal
            return StrategySignal(
                action='hold',
                confidence=0.5,
                price=current_price,
                timestamp=datetime.now(),
                indicators={
                    'supertrend': current_st,
                    'atr': atr[-1],
                    'direction': current_direction
                },
                reasoning="No trend change detected"
            )

        except Exception as e:
            logger.error(f"Error generating SuperTrend signal: {e}")
            return None

    def _calculate_atr(self, high: List[float], low: List[float], close: List[float]) -> List[float]:
        """Calculate Average True Range"""
        tr_list = []

        for i in range(1, len(close)):
            tr = max(
                high[i] - low[i],
                abs(high[i] - close[i-1]),
                abs(low[i] - close[i-1])
            )
            tr_list.append(tr)

        # Simple moving average of TR
        atr = []
        for i in range(len(tr_list)):
            if i < self.atr_period - 1:
                atr.append(np.mean(tr_list[:i+1]))
            else:
                atr.append(np.mean(tr_list[i-self.atr_period+1:i+1]))

        return atr

    def _calculate_bands(
        self,
        high: List[float],
        low: List[float],
        atr: List[float]
    ) -> tuple:
        """Calculate SuperTrend bands"""
        basic_upper = []
        basic_lower = []

        for i in range(len(atr)):
            hl_avg = (high[i+1] + low[i+1]) / 2
            basic_upper.append(hl_avg + self.multiplier * atr[i])
            basic_lower.append(hl_avg - self.multiplier * atr[i])

        return basic_upper, basic_lower

    def _calculate_supertrend(
        self,
        close: List[float],
        upper: List[float],
        lower: List[float]
    ) -> tuple:
        """Calculate SuperTrend indicator and direction"""
        supertrend = [lower[0]]
        direction = [1]  # 1 = uptrend, -1 = downtrend

        for i in range(1, len(close) - 1):
            prev_st = supertrend[-1]
            prev_dir = direction[-1]

            # Update bands
            curr_upper = upper[i]
            curr_lower = lower[i]

            if prev_dir == 1:
                curr_lower = max(curr_lower, lower[i-1])
            else:
                curr_upper = min(curr_upper, upper[i-1])

            # Determine new direction
            if close[i] <= curr_lower:
                new_dir = -1
                new_st = curr_upper
            elif close[i] >= curr_upper:
                new_dir = 1
                new_st = curr_lower
            else:
                new_dir = prev_dir
                new_st = curr_upper if new_dir == -1 else curr_lower

            supertrend.append(new_st)
            direction.append(new_dir)

        return supertrend, direction

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest SuperTrend strategy"""

        # Placeholder for backtesting
        # Future enhancement: Implement full backtesting with historical data

        return {
            'strategy': 'SuperTrend',
            'symbol': symbol,
            'period': period,
            'total_return': 0.245,  # 24.5%
            'win_rate': 0.62,
            'sharpe_ratio': 2.1,
            'max_drawdown': -0.083,
            'num_trades': 45,
            'avg_trade_duration': 3.2,
            'note': 'Placeholder backtest results - implement full backtesting'
        }


class RLStrategy(BaseStrategy):
    """
    Reinforcement Learning Strategy

    Uses trained RL agent for trading decisions.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.model_path = self.parameters.get('model_path', None)
        self._agent = None

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal using RL agent"""

        # Placeholder for RL agent
        # Future enhancement: Load and use actual trained RL model

        return StrategySignal(
            action='hold',
            confidence=0.6,
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={'rl_score': 0.6},
            reasoning="RL agent decision (placeholder)"
        )

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest RL strategy"""

        return {
            'strategy': 'RL',
            'symbol': symbol,
            'period': period,
            'note': 'RL backtesting to be implemented'
        }


class MultiFactorStrategy(BaseStrategy):
    """
    Multi-Factor Strategy

    Combines multiple technical indicators and factors.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.factors = self.parameters.get('factors', ['trend', 'momentum', 'volatility'])
        self.weights = self.parameters.get('weights', [0.4, 0.4, 0.2])

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from multiple factors"""

        # Calculate factor scores
        trend_score = self._calculate_trend_score(market_data)
        momentum_score = self._calculate_momentum_score(market_data)
        volatility_score = self._calculate_volatility_score(market_data)

        # Weighted combination
        combined_score = (
            trend_score * self.weights[0] +
            momentum_score * self.weights[1] +
            volatility_score * self.weights[2]
        )

        # Determine action
        if combined_score > 0.6:
            action = 'buy'
        elif combined_score < 0.4:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=abs(combined_score - 0.5) * 2,
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={
                'combined_score': combined_score,
                'trend_score': trend_score,
                'momentum_score': momentum_score,
                'volatility_score': volatility_score
            },
            reasoning=f"Multi-factor score: {combined_score:.2f}"
        )

    def _calculate_trend_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate trend factor score"""
        # Placeholder - implement actual trend calculation
        return 0.7

    def _calculate_momentum_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate momentum factor score"""
        # Placeholder - implement actual momentum calculation
        return 0.6

    def _calculate_volatility_score(self, market_data: Dict[str, Any]) -> float:
        """Calculate volatility factor score"""
        # Placeholder - implement actual volatility calculation
        return 0.5

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest multi-factor strategy"""

        return {
            'strategy': 'MultiFactor',
            'symbol': symbol,
            'period': period,
            'note': 'Multi-factor backtesting to be implemented'
        }


class HybridStrategy(BaseStrategy):
    """
    Hybrid Strategy

    Combines multiple strategies with ensemble logic.
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.strategies = [
            SuperTrendStrategy(config),
            MultiFactorStrategy(config)
        ]

    def generate_signal(self, market_data: Dict[str, Any]) -> Optional[StrategySignal]:
        """Generate signal from ensemble of strategies"""

        # Get signals from all strategies
        signals = []
        for strategy in self.strategies:
            signal = strategy.generate_signal(market_data)
            if signal:
                signals.append(signal)

        if not signals:
            return None

        # Ensemble logic: majority vote weighted by confidence
        buy_score = sum(s.confidence for s in signals if s.action == 'buy')
        sell_score = sum(s.confidence for s in signals if s.action == 'sell')
        hold_score = sum(s.confidence for s in signals if s.action == 'hold')

        max_score = max(buy_score, sell_score, hold_score)

        if max_score == buy_score:
            action = 'buy'
        elif max_score == sell_score:
            action = 'sell'
        else:
            action = 'hold'

        return StrategySignal(
            action=action,
            confidence=max_score / len(signals),
            price=market_data.get('close', [0])[-1],
            timestamp=datetime.now(),
            indicators={'ensemble_score': max_score},
            reasoning=f"Ensemble decision from {len(signals)} strategies"
        )

    def backtest(self, symbol: str, period: str) -> Dict[str, Any]:
        """Backtest hybrid strategy"""

        return {
            'strategy': 'Hybrid',
            'symbol': symbol,
            'period': period,
            'note': 'Hybrid backtesting to be implemented'
        }


# Strategy registry
STRATEGY_REGISTRY = {
    'supertrend': SuperTrendStrategy,
    'rl_agent': RLStrategy,
    'multi_factor': MultiFactorStrategy,
    'hybrid': HybridStrategy
}


def get_strategy(strategy_name: str, config: Dict[str, Any]) -> BaseStrategy:
    """Factory function to get strategy instance"""

    strategy_class = STRATEGY_REGISTRY.get(strategy_name)

    if strategy_class is None:
        raise ValueError(f"Unknown strategy: {strategy_name}")

    return strategy_class(config)


def list_strategies() -> List[str]:
    """List available strategies"""
    return list(STRATEGY_REGISTRY.keys())


if __name__ == "__main__":
    # Example usage
    config = {
        'parameters': {
            'atr_period': 10,
            'multiplier': 3.0
        }
    }

    strategy = SuperTrendStrategy(config)

    # Mock market data
    market_data = {
        'high': [100 + i for i in range(20)],
        'low': [99 + i for i in range(20)],
        'close': [99.5 + i for i in range(20)]
    }

    signal = strategy.generate_signal(market_data)
    if signal:
        print(f"Signal: {signal.action} at {signal.price} (confidence: {signal.confidence})")
